version: "3"

services:
    nginx:
        container_name: nginx
        image: nginx
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/conf.d/backend.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/log/:/var/log/nginx
        depends_on:
            - php
            - mysql
        ports:
            - 80:80

    php:
        container_name: php
        image: blog_php
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini

    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: blog
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./docker/mysql:/var/lib/mysql
        ports:
            - 3306:3306

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        ports:
            - 8081:80
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: root

    mailhog:
        image: mailhog/mailhog:latest
        container_name: mailhog
        ports:
            - 1025:1025
            - 8025:8025
       
    minio:
        image: minio/minio
        container_name: c-minio
        ports:
            - "9000:9000"
            - "9001:9001"
        volumes:
            - ./docker/minio:/data
        environment:
            MINIO_ROOT_USER: root
            MINIO_ROOT_PASSWORD: 123hiep123
        command: server --console-address ":9001" /data

